--//CREATION OF TABLES

--// 1) CREATION OF WORK DEPARTMENT TABLE

CREATE TABLE [dbo].[WORK_DEPARTMENT_TBL](
	[DEP_ID] [int] NOT NULL,
	[TITLE] [varchar](100) NULL
) ON [PRIMARY]


--//2) CREATION OF WORK DEPARTMENT DETAIL TABLE
CREATE TABLE [dbo].[WORK_DTL_TBL](
	[WORK_DTL_ID] [int] NOT NULL,
	[CODE] [varchar](50) NULL,
	[LOCATION] [varchar](50) NOT NULL,
	[DEPARTMENT] [varchar](50) NOT NULL,
	[POSTEDDATE] [date] NULL,
	[CLOSINGDATE] [date] NULL,
 CONSTRAINT [PK_WORK_DTL_TBL] PRIMARY KEY CLUSTERED 
(
	[WORK_DTL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--//3) CREATION OF DEPARTMENT LOCATION TABLE
CREATE TABLE [dbo].[WORK_LOCATION_TBL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [varchar](50) NULL,
	[CITY] [varchar](50) NULL,
	[STATE] [varchar](50) NULL,
	[COUNTRY] [varchar](50) NULL,
	[ZIP] [varchar](10) NULL,
	[LOC_ID] [int] NULL,
 CONSTRAINT [PK_LOCATION_TBL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

--//4) CREATION OF WORK TABLE
CREATE TABLE [dbo].[WORK_TBL](
	[WORK_ID] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [varchar](100) NULL,
	[LOCATIONID] [int] NULL,
	[DEPARTMENTID] [int] NULL,
	[CLOSINGDATE] [date] NULL,
	[DESCRIPTION] [varchar](200) NULL,
 CONSTRAINT [PK_WORK_TBL] PRIMARY KEY CLUSTERED 
(
	[WORK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


--//INSERTION OF DATA IN TABLE

--//1) INSERTION IN WORK_DEPARTMENT_TBL
INSERT [dbo].[WORK_DEPARTMENT_TBL] ([DEP_ID], [TITLE]) VALUES (2085, N'Software Dev')
INSERT [dbo].[WORK_DEPARTMENT_TBL] ([DEP_ID], [TITLE]) VALUES (2084, N'Software Test')
INSERT [dbo].[WORK_DEPARTMENT_TBL] ([DEP_ID], [TITLE]) VALUES (2086, N'Software Management')

--//2) INSERTION IN WORK_DTL_TBL
INSERT [dbo].[WORK_DTL_TBL] ([WORK_DTL_ID], [CODE], [LOCATION], [DEPARTMENT], [POSTEDDATE], [CLOSINGDATE]) VALUES (1, N'WORK-01', N'UK', N'Web Development', CAST(N'2022-03-12' AS Date), CAST(N'2022-04-21' AS Date))
INSERT [dbo].[WORK_DTL_TBL] ([WORK_DTL_ID], [CODE], [LOCATION], [DEPARTMENT], [POSTEDDATE], [CLOSINGDATE]) VALUES (2, N'WORK-02', N'India', N'Web Testing', CAST(N'2022-03-12' AS Date), CAST(N'2022-04-21' AS Date))
INSERT [dbo].[WORK_DTL_TBL] ([WORK_DTL_ID], [CODE], [LOCATION], [DEPARTMENT], [POSTEDDATE], [CLOSINGDATE]) VALUES (3, N'WORK-03', N'Pakistan', N'Web Managment', CAST(N'2022-03-12' AS Date), CAST(N'2022-04-21' AS Date))

--//3) INSERTION IN WORK_LOCATION_TBL
SET IDENTITY_INSERT [dbo].[WORK_LOCATION_TBL] ON 

INSERT [dbo].[WORK_LOCATION_TBL] ([ID], [TITLE], [CITY], [STATE], [COUNTRY], [ZIP], [LOC_ID]) VALUES (1, N'US Head office', N'Balitmore', N'MD', N'US', N'21202', 10030)
INSERT [dbo].[WORK_LOCATION_TBL] ([ID], [TITLE], [CITY], [STATE], [COUNTRY], [ZIP], [LOC_ID]) VALUES (2, N'India Head Ofiice', N'Mapusa', N'GOa', N'India', N'403507', 10031)
INSERT [dbo].[WORK_LOCATION_TBL] ([ID], [TITLE], [CITY], [STATE], [COUNTRY], [ZIP], [LOC_ID]) VALUES (3, N'Pakistan Head Office', N'CityA', N'StateA', N'Pakistan', N'112458', 10032)

SET IDENTITY_INSERT [dbo].[WORK_LOCATION_TBL] OFF

--//4) INSERTION IN WORK_TBL
SET IDENTITY_INSERT [dbo].[WORK_TBL] ON 

INSERT [dbo].[WORK_TBL] ([WORK_ID], [TITLE], [LOCATIONID], [DEPARTMENTID], [CLOSINGDATE], [DESCRIPTION]) VALUES (1, N'Software Engineer', 10030, 2085, CAST(N'2022-04-21' AS Date), N'Full Stack Developer')
INSERT [dbo].[WORK_TBL] ([WORK_ID], [TITLE], [LOCATIONID], [DEPARTMENTID], [CLOSINGDATE], [DESCRIPTION]) VALUES (2, N'Senior Software Developer', 10031, 2084, CAST(N'2022-04-20' AS Date), N'Full stack Developer')
INSERT [dbo].[WORK_TBL] ([WORK_ID], [TITLE], [LOCATIONID], [DEPARTMENTID], [CLOSINGDATE], [DESCRIPTION]) VALUES (3, N'Software Engineer', 10032, 2086, CAST(N'2022-04-15' AS Date), N'Back-End Developer')

SET IDENTITY_INSERT [dbo].[WORK_TBL] OFF


ALTER TABLE [dbo].[WORK_TBL]  WITH CHECK ADD  CONSTRAINT [FK_WORK_TBL_WORK_TBL] FOREIGN KEY([WORK_ID])
REFERENCES [dbo].[WORK_TBL] ([WORK_ID])

ALTER TABLE [dbo].[WORK_TBL] CHECK CONSTRAINT [FK_WORK_TBL_WORK_TBL]


--//stored procedure
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE    PROCEDURE [dbo].[USP_GET_WORK_DTLS]
	@WORKId INT
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TMPCUSTOMER TABLE (
		 ID INT PRIMARY KEY IDENTITY(1, 1)
		 ,WORK_ID INT 
		,CODE VARCHAR(100)
		,TITLE VARCHAR(100)
		,LOCATION VARCHAR(50) NOT NULL
		,DEPARTMENT VARCHAR(50) NOT NULL
		,POSTEDDATE DATE NULL
		,CLOSINGDATE DATE NULL
		)


		INSERT INTO @TMPCUSTOMER (
			 WORK_ID  
			,CODE
			,TITLE 
			,LOCATION 
			,DEPARTMENT
			,POSTEDDATE
			,CLOSINGDATE
			)
		SELECT WORK_ID
			,CODE
			,TITLE
			,LOCATION
			,DEPARTMENT
			,POSTEDDATE
			,JT.CLOSINGDATE
		FROM DBO.WORK_TBL JT
		INNER JOIN [dbo].[WORK_DTL_TBL] JDT on JT.WORK_ID = JDT.WORK_DTL_ID
		WHERE WORK_ID = @WORKId; 
	 

	SELECT WORK_ID  
			,CODE
			,TITLE 
			,LOCATION 
			,DEPARTMENT
			,POSTEDDATE
			,CLOSINGDATE
	FROM @TMPCUSTOMER

	

END

GO



SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    PROCEDURE [dbo].[USP_GET_WORK_LIST]
	@LocationId INT ,
	@DepartmentId INT 
	
AS
BEGIN
	SET NOCOUNT ON;

	DECLARE @TMPCUSTOMER TABLE (
		 ID INT PRIMARY KEY IDENTITY(1, 1)
		 ,WORK_ID INT 
		,CODE VARCHAR(100)
		,TITLE VARCHAR(100)
		,LOCATION VARCHAR(50) NOT NULL
		,DEPARTMENT VARCHAR(50) NOT NULL
		,POSTEDDATE DATE NULL
		,CLOSINGDATE DATE NULL
		)

		INSERT INTO @TMPCUSTOMER (
			 WORK_ID  
			,CODE
			,TITLE 
			,LOCATION 
			,DEPARTMENT
			,POSTEDDATE
			,CLOSINGDATE
			)
		SELECT WORK_ID
			,CODE
			,TITLE
			,LOCATION
			,DEPARTMENT
			,POSTEDDATE
			,JT.CLOSINGDATE
		FROM DBO.WORK_TBL JT
		INNER JOIN [dbo].[WORK_DTL_TBL] JDT on JT.WORK_ID = JDT.WORK_DTL_ID
		WHERE LOCATIONID = @LocationId or DEPARTMENTID = @DepartmentId;
	 
	SELECT WORK_ID  
			,CODE
			,TITLE 
			,LOCATION 
			,DEPARTMENT
			,POSTEDDATE
			,CLOSINGDATE
	FROM @TMPCUSTOMER
END



SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USP_INS_UPD_WORKS]
	-- Add the parameters for the stored procedure here
	@Id INT,
	@Title varchar(MAX),
	@Description varchar(MAX),
	@LocationId varchar(50),
	@DepartmentId varchar(50),
	@ClosingDate varchar(50)
	
AS
BEGIN
SET NOCOUNT ON;

  IF(@Id = 0)
  BEGIN
  INSERT INTO [dbo].[WORK_TBL]
           (TITLE
           ,DESCRIPTION
           ,LOCATIONID
           ,DEPARTMENTID
           ,CLOSINGDATE)
     VALUES
           (@Title
           ,@Description
           ,@LocationId
           ,@DepartmentId
           ,@ClosingDate
           )
	END
	ELSE
	BEGIN
	if exists(select WORK_ID from WORK_TBL where WORK_ID = @Id)
	BEGIN
	UPDATE [dbo].[WORK_TBL] set TITLE = @Title,DESCRIPTION = @Description,LOCATIONID = @LocationId, DEPARTMENTID = @DepartmentId, CLOSINGDATE = @ClosingDate
	WHERE WORK_ID = @Id;
	END
	END
END
GO

